# Generated by Django 6.0.1 on 2026-01-24 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama penyakit dalam Bahasa Inggris', max_length=100, unique=True)),
                ('nama_indonesia', models.CharField(help_text='Nama penyakit dalam Bahasa Indonesia', max_length=100)),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat tentang penyakit')),
                ('gejala', models.JSONField(default=list, help_text='Daftar gejala penyakit')),
                ('penanganan_organik', models.JSONField(default=list, help_text='Cara penanganan organik')),
                ('penanganan_kimia', models.JSONField(default=list, help_text='Cara penanganan kimia')),
                ('pencegahan', models.JSONField(default=list, help_text='Langkah-langkah pencegahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penyakit',
                'verbose_name_plural': 'Penyakit',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ProfilPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, help_text='Foto profil pengguna', null=True, upload_to='profil/')),
                ('nomor_telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
        migrations.CreateModel(
            name='RiwayatDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(help_text='Gambar yang diupload untuk deteksi', upload_to='deteksi/%Y/%m/%d/')),
                ('nama_kelas', models.CharField(help_text='Nama kelas hasil prediksi', max_length=100)),
                ('kepercayaan', models.FloatField(help_text='Nilai kepercayaan prediksi (0-1)')),
                ('status_sehat', models.BooleanField(default=False, help_text='Apakah tanaman sehat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penyakit', models.ForeignKey(blank=True, help_text='Penyakit yang terdeteksi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deteksi', to='api.penyakit')),
                ('user', models.ForeignKey(help_text='Pengguna yang melakukan deteksi', on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_deteksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Deteksi',
                'verbose_name_plural': 'Riwayat Deteksi',
                'ordering': ['-created_at'],
            },
        ),
    ]
